#!/usr/bin/env node
// Regenerates data/data.js from the JSON files in data/.
// Run after editing any data/*.json:  node scripts/embed-data.js
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const sources = {
  services: 'data/services.json',
  metrics: 'data/metrics.json',
  accounts: 'data/accounts.json',
};

const bundle = {};
for (const [key, rel] of Object.entries(sources)) {
  bundle[key] = JSON.parse(fs.readFileSync(path.join(root, rel), 'utf8'));
}

const banner =
  '// Auto-generated by scripts/embed-data.js — do not edit by hand.\n' +
  '// Embedded copy of data/*.json so the dashboard works when opened\n' +
  '// directly from disk (file://), where fetch() is unavailable.\n';

fs.writeFileSync(
  path.join(root, 'data/data.js'),
  `${banner}window.EmbeddedData = ${JSON.stringify(bundle, null, 2)};\n`
);

console.log('data/data.js regenerated from', Object.values(sources).join(', '));
